site_name: Backend Engineering Notes
site_description: Practical backend engineering notes
site_author: labeeb

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
  # move search to sidebar
  search:
    provider: lunr
    placement: sidebar
  # make sidebar sub-items collapsed by default
  navigation.expand: false

nav:
  - Home:
      - Main: index.md
      - Networking:
          - Overview: networking/index.md
          - OSI Model: networking/osi.md
      - Architecture:
          - Overview: architecture/layered.md
          - Layered: architecture/layered.md
          - Microservices: architecture/microservices.md
  - Databases:
      - Indexing Topics: databases/indexing.md
