site_name: Backend Engineering Notes
site_description: Practical backend engineering notes
site_author: labeeb

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - header.autohide

# Move search to sidebar
search:
  provider: lunr
  placement: sidebar

# Make sidebar sub-items collapsed by default
navigation.expand: false

# Include custom CSS
extra_css:
  - css/extra.css

# Include custom JS for avatar under first heading
extra_javascript:
  - js/author-avatar.js

nav:
  - Home:
      - Main: index.md
      - Networking:
          - Overview: networking/index.md
          - OSI Model: networking/osi.md
          - OSI Layer's Unit of Data: networking/osi-unit-of-data.md
      - Databases:
          - Overview: databases/overview.md
          - Database Optimization From Indexes to Partitioning: databases/Database-Optimization-From-Indexes-to-Partitioning.md
          - Optimistic vs Pessimistic Locking: databases/optimistic-vs-pessimistic-locking.md
      - Security:
          - Overview: security/overview.md
      - Architecture:
          - Overview: architecture/overview.md
          - Layered: architecture/layered.md
          - Microservices: architecture/microservices.md
          - Layered Architecture & Exception Handling Guide: architecture/layered-architecture-exceptions-handling.md
          - Domain Exceptions in Typescript: architecture/domain-exceptions-in-ts.md
