site_name: Backend Engineering Notes
site_description: Practical backend engineering notes
site_author: labeeb

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - header.autohide

# Move search to sidebar
search:
  provider: lunr
  placement: sidebar

# Make sidebar sub-items collapsed by default
navigation.expand: false

# Include custom CSS
extra_css:
  - css/extra.css

nav:
  - Home:
      - Main: index.md
      - Networking:
          - Overview: networking/index.md
          - OSI Model: networking/osi.md
          - OSI Layer's Unit of Data: networking/osi-unit-of-data.md
      - Databases:
          - Overview: databases/overview.md
          - Database Optimization From Indexes to Partitioning: databases/Database-Optimization-From-Indexes-to-Partitioning.md
  - Architecture:
      - Overview: architecture/layered.md
      - Layered: architecture/layered.md
      - Microservices: architecture/microservices.md
