site_name: Backend Engineering Notes
site_description: Practical backend engineering notes
site_author: labeeb

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy
nav:
  - Home:
    - Main: index.md
    - Introduction: introduction.md
    - Getting Started: getting-started.md  
  - Architecture:
    - Layered: architecture/layered.md
    - Microservices: architecture/microservices.md
  - Databases:
    - Indexing: databases/indexing.md
